version: '3.3'

# docker compose --project-name my-project -f docker-compose.yml -f docker-compose.Development.yml up -d

services:
  smartconfig:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "com.centurylinklabs.watchtower.enable=false"

networks:
  proxy:
    external: true
    